In [ ]:
# Q 1:
import numpy as np


a = np.array([1, 2, 4, 7, 8])
list1=a.tolist()
print(list1)


[1, 2, 4, 7, 8]


In [ ]:
# Q 2 :
import numpy as np
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
a=a.reshape(3,3)
n1=np.trace(a)
print("this original array : ")
print(a,"and this with trace fonction",n1)
a1=a[0][0]
a2=a[1][1]
a3=a[2][2]

print("and with hand : ",a1+a2+a3)


this original array : 
[[0 1 2]
 [3 4 5]
 [6 7 8]] and this with trace fonction 12
and with hand :  12


In [ ]:
# Q 3
import numpy as np
a = [[1,2],[3,5]]
x=[2]
for i in a:
  if x<i:
    print("then",i,"are higher than",x)



then [3, 5] are higher than [2]


In [ ]:
# Q 4
import numpy as np
A=np.array([(1, 2), (3, 4), (5,6)])
A.shape
B=np.array([(1, 2), (3, 4), (5,6)])
B.shape
C=A+B
print("this new array :")
print(C)



this new array :
[[ 2  4]
 [ 6  8]
 [10 12]]


In [2]:
# Q 5 :
import numpy as np
 # now we made  normal matrix
arr=np.arange(12).reshape(3,4)
print(arr)
 # use mean fuction ....
rowmean = np.mean(arr, axis=1)
mean0=rowmean[0]
mean1=rowmean[1]
mean2=rowmean[2]
print(mean0)
print(mean1)
print(mean2)



 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
1.5
5.5
9.5
